status = [
  "test-os (1.9, ubuntu-latest)",
  "test-os (1.9, windows-latest)",
  "test-os (1.9, macos-latest)",
  "buildkite/climatimesteppers-ci",
  "format",
  "docbuild"
]
delete_merged_branches = true
timeout_sec = 12600
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
