agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_10_09
  partition: expansion

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate docs"
      - "julia --project=docs -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Package status"
      - "julia --project -e 'using Pkg; Pkg.status()'"


  # - label: "init gpu env"
  #   key: "init_gpu_env"
  #   command:
  #     - echo "--- Configure MPI"
  #     - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

  #     - echo "--- Instantiate project"
  #     - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

  #     - echo "--- Instantiate test"
  #     - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile()'"

  #     - echo "--- Initialize CUDA runtime"
  #     - "julia --project -e 'using CUDA; CUDA.precompile_runtime(); CUDA.versioninfo()'"

  #     - echo "--- Package status"
  #     - "julia --project -e 'using Pkg; Pkg.status()'"
  #     slurm_gres: "gpu:1"

  - wait

  - group: "Unit tests"
    steps:

      - label: "unit: sparse_containers"
        command: "julia --project=test --check-bounds=yes test/sparse_containers.jl"
        artifact_paths: "output/*"

      - label: "unit: fused_increment"
        command: "julia --project=test --check-bounds=yes test/fused_increment.jl"
        artifact_paths: "output/*"

      - label: "unit: test_newtons_method"
        command: "julia --project=test --check-bounds=yes test/test_newtons_method.jl"
        artifact_paths: "output/*"

      - label: "unit: single_column_ARS_test"
        command: "julia --project=test --check-bounds=yes test/single_column_ARS_test.jl"
        artifact_paths: "output/*"

      - label: "unit: callbacks"
        command: "julia --project=test --check-bounds=yes test/callbacks.jl"
        artifact_paths: "output/*"

      - label: "unit: aqua"
        command: "julia --project=test --check-bounds=yes test/aqua.jl"
        artifact_paths: "output/*"

      - label: "unit: integrator"
        command: "julia --project=test --check-bounds=yes test/integrator.jl"
        artifact_paths: "output/*"

      - label: "unit: test_convergence_checker"
        command: "julia --project=test --check-bounds=yes test/test_convergence_checker.jl"
        artifact_paths: "output/*"

  - group: "Test convergence"
    steps:

      - label: "conv: lsrk"
        command: "julia --project=test --check-bounds=yes test/convergence_lsrk.jl"

  - group: "Tabulate convergence"
    steps:

      - label: "conv: tabulate_convergence_orders_multirate"
        command: "julia --project=test --check-bounds=yes test/tabulate_convergence_orders_multirate.jl"

      - label: "conv: tabulate_convergence_orders_rosenbrock"
        command: "julia --project=test --check-bounds=yes test/tabulate_convergence_orders_rosenbrock.jl"

      - label: "conv: tabulate_convergence_orders_imex_ssp"
        command: "julia --project=test --check-bounds=yes test/tabulate_convergence_orders_imex_ssp.jl"

      - label: "conv: tabulate_convergence_orders_imex_ark"
        command: "julia --project=test --check-bounds=yes test/tabulate_convergence_orders_imex_ark.jl"


      # - label: "GPU tests"
      #   command:
      #     - "julia --project=test --check-bounds=yes test/runtests.jl CuArray"
      #   artifact_paths: "output/*"
      #     slurm_gres: "gpu:1"

  - group: "Performance"
    steps:

      - label: "Perf: Flame graph (1D diffusion)"
        command: "julia --project=perf perf/flame.jl --job_id diffusion_1D"
        artifact_paths: "diffusion_1D/*"

      - label: "Perf: Jet graph (ode fun)"
        command: "julia --project=perf perf/jet.jl --problem ode_fun"

      - label: "Perf: Jet (forward euler)"
        command: "julia --project=perf perf/jet.jl --problem fe"

      - label: "Perf: Jet (clima diffusion 2D)"
        command: "julia --project=perf perf/jet.jl --problem diffusion2d"

      - label: "Perf: Benchmark"
        command: "julia --project=perf perf/benchmark.jl"


  - group: "Limiters analysis"
    steps:

      - label: "Limiters analysis: SSP333_LT_HT"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg SSP333 --use_limiter true --use_hyperdiffusion true"

      - label: "Limiters analysis: ARS343_LT_HT"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg ARS343 --use_limiter true --use_hyperdiffusion true"

      - label: "Limiters analysis: SSP333_LF_HT"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg SSP333 --use_limiter false --use_hyperdiffusion true"

      - label: "Limiters analysis: ARS343_LF_HT"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg ARS343 --use_limiter false --use_hyperdiffusion true"

      - label: "Limiters analysis: SSP333_LT_HF"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg SSP333 --use_limiter true --use_hyperdiffusion false"

      - label: "Limiters analysis: ARS343_LT_HF"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg ARS343 --use_limiter true --use_hyperdiffusion false"

      - label: "Limiters analysis: SSP333_LF_HF"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg SSP333 --use_limiter false --use_hyperdiffusion false"

      - label: "Limiters analysis: ARS343_LF_HF"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/limiter_analysis.jl --alg ARS343 --use_limiter false --use_hyperdiffusion false"

  - group: "Convergence"
    steps:

      - label: "Convergence: SSP22Heuns"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP22Heuns"
        soft_fail: true

      - label: "Convergence: SSP33ShuOsher"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP33ShuOsher"

      - label: "Convergence: RK4"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg RK4"

      - label: "Convergence: ARK2GKC"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARK2GKC"

      - label: "Convergence: ARS111"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS111"

      - label: "Convergence: ARS121"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS121"

      - label: "Convergence: ARS122"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS122"

      - label: "Convergence: ARS222"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS222"

      - label: "Convergence: ARS232"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS232"

      - label: "Convergence: ARS233"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS233"

      - label: "Convergence: ARS343"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS343"

      - label: "Convergence: ARS443"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg ARS443"

      - label: "Convergence: SSP222"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP222"
        soft_fail: true

      - label: "Convergence: SSP322"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP322"

      - label: "Convergence: SSP332"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP332"

      - label: "Convergence: SSP333"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP333"

      - label: "Convergence: SSP433"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSP433"

      - label: "Convergence: DBM453"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg DBM453"

      - label: "Convergence: HOMMEM1"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg HOMMEM1"

      - label: "Convergence: IMKG232a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG232a"

      - label: "Convergence: IMKG232b"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG232b"

      - label: "Convergence: IMKG242a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG242a"
        soft_fail: true

      - label: "Convergence: IMKG242b"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG242b"

      - label: "Convergence: IMKG243a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG243a"

      - label: "Convergence: IMKG252a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG252a"

      - label: "Convergence: IMKG252b"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG252b"

      - label: "Convergence: IMKG253a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG253a"

      - label: "Convergence: IMKG253b"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG253b"

      - label: "Convergence: IMKG254a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG254a"

      - label: "Convergence: IMKG254b"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG254b"

      - label: "Convergence: IMKG254c"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG254c"

      - label: "Convergence: IMKG342a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG342a"

      - label: "Convergence: IMKG343a"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg IMKG343a"

      - label: "Convergence: SSPKnoth"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/report_gen_alg.jl --alg SSPKnoth"

  - wait

  - group: "Summaries"
    steps:

      - label: "Summarize convergence"
        command: "julia --color=yes --check-bounds=yes --project=docs docs/src/dev/summarize_convergence.jl"
        artifact_paths: "output/*"

      - label: "Summarize limiter analysis"
        command: "julia --color=yes --project=docs docs/src/dev/limiter_summary.jl"
        artifact_paths: "output/*"
