
agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.8.5 openmpi/4.1.1 cuda/11.3 hdf5/1.12.1-ompi411

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_CUDA_USE_BINARYBUILDER: false
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Package status"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test --check-bounds=yes test/runtests.jl"
    artifact_paths: "output/*"

  - label: "Flame graph (1D diffusion)"
    command:
      - "julia --project=perf perf/flame.jl --job_id diffusion_1D"
    artifact_paths: "diffusion_1D/*"

  - label: "Jet graph (ode fun)"
    command:
      - "julia --project=perf perf/jet.jl --problem ode_fun"

  - label: "Jet (forward euler)"
    command:
      - "julia --project=perf perf/jet.jl --problem fe"

  - label: "Benchmark"
    command:
      - "julia --project=perf perf/benchmark.jl"

  - label: "GPU tests"
    command:
      - julia --project=test --check-bounds=yes test/simple_gpu.jl
    artifact_paths: "output/*"
    agents:
      slurm_gpus: 1