agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_05_27

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  # JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate docs"
      - "julia --project=docs -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Package status"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_gpus: 1

  - wait

  - label: "CPU tests"
    command: "julia --project=test --check-bounds=yes test/runtests.jl"
    artifact_paths: "output/*"

  - label: "Deformational flow limiter test (CPU)"
    command:
      - "julia --project=docs --check-bounds=yes docs/src/test_deformational_flow.jl CPU"
    artifact_paths: "output_CPU/*"

  - label: "Deformational flow limiter test (GPU)"
    command:
      - "julia --project=docs docs/src/test_deformational_flow.jl GPU"
    artifact_paths: "output_GPU/*"
    agents:
      slurm_gpus: 1

  - label: "Deformational flow limiter test (GPU w/ check-bounds)"
    command:
      - "julia --project=docs --check-bounds=yes docs/src/test_deformational_flow.jl GPU_checkbounds"
    artifact_paths: "output_GPU_checkbounds/*"
    agents:
      slurm_gpus: 1

  - label: "Flame graph (1D diffusion)"
    command: "julia --project=perf perf/flame.jl --job_id diffusion_1D"
    artifact_paths: "diffusion_1D/*"

  - label: "Jet graph (ode fun)"
    command: "julia --project=perf perf/jet.jl --problem ode_fun"

  - label: "Jet (forward euler)"
    command: "julia --project=perf perf/jet.jl --problem fe"

  - label: "Jet (clima diffusion 2D)"
    command: "julia --project=perf perf/jet.jl --problem diffusion2d"

  - label: "Benchmark"
    command: "julia --project=perf perf/benchmark.jl"
