agents:
  queue: central
  slurm_mem: 8G
  modules: julia/1.10.0 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 nsight-systems/2023.3.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  JULIA_NVTX_CALLBACKS: gc
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_CPU_TARGET: 'broadwell;skylake;icelake;cascadelake;epyc'
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_CUDA_MEMORY_POOL: none
  JULIA_MPI_HAS_CUDA: "true"
  MPITRAMPOLINE_LIB: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/lib64/libmpiwrapper.so"
  MPITRAMPOLINE_MPIEXEC: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/bin/mpiwrapperexec"

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      # - echo "--- Configure MPI"
      # - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"
      # force the initialization of the CUDA runtime as it is lazily loaded by default
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

      - echo "--- Package status"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  # - label: "init gpu env"
  #   key: "init_gpu_env"
  #   command:
  #     - echo "--- Configure MPI"
  #     - julia -e 'using Pkg; Pkg.add("MPIPreferences"); using MPIPreferences; use_system_binary()'

  #     - echo "--- Instantiate project"
  #     - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true)'"

  #     - echo "--- Instantiate test"
  #     - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\"); Pkg.instantiate(;verbose=true); Pkg.precompile()'"

  #     - echo "--- Initialize CUDA runtime"
  #     - "julia --project -e 'using CUDA; CUDA.precompile_runtime(); CUDA.versioninfo()'"

  #     - echo "--- Package status"
  #     - "julia --project -e 'using Pkg; Pkg.status()'"
  #   agents:
  #     config: gpu
  #     queue: central
  #     slurm_ntasks: 1
  #     slurm_gres: "gpu:1"

  - wait

  - label: "CPU tests"
    command:
      - "julia --project=test --check-bounds=yes test/runtests.jl"
    artifact_paths: "output/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  # - label: "GPU tests"
  #   command:
  #     - "julia --project=test --check-bounds=yes test/runtests.jl CuArray"
  #   artifact_paths: "output/*"
  #   agents:
  #     config: gpu
  #     queue: central
  #     slurm_ntasks: 1
  #     slurm_gres: "gpu:1"

  - label: "Flame graph (1D diffusion)"
    command:
      - "julia --project=perf perf/flame.jl --job_id diffusion_1D"
    artifact_paths: "diffusion_1D/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Jet graph (ode fun)"
    command:
      - "julia --project=perf perf/jet.jl --problem ode_fun"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Jet (forward euler)"
    command:
      - "julia --project=perf perf/jet.jl --problem fe"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Benchmark"
    command:
      - "julia --project=perf perf/benchmark.jl"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
