env:
  JULIA_VERSION: "1.7.1"
  CUDA_VERSION: "11.2"
  OPENMPI_VERSION: "4.1.1"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"

steps:
  - label: "init cpu env"
    key: "init_cpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path=\".\")'"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile(;strict=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "init gpu env"
    key: "init_gpu_env"
    command:
      - "echo $JULIA_DEPOT_PATH"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.precompile()'"
      - "julia --project -e 'using CUDA; CUDA.versioninfo()'"
      - "julia --project -e 'using CUDA; CUDA.precompile_runtime()'"
      - "julia --project -e 'using Pkg; Pkg.status()'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - wait

  - label: "Unit tests and plots"
    command:
      - "julia --project -e 'using Pkg; Pkg.test()'"
    artifact_paths: "test/output/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "GPU tests"
    command:
      - "julia --project -e 'using Pkg; Pkg.test(;test_args=[\"CuArray\"])'"
    agents:
      config: gpu
      queue: central
      slurm_ntasks: 1
      slurm_gres: "gpu:1"

  - label: "Flame graph (ode fun)"
    command:
      - "julia --project=perf perf/flame.jl --job_id ode_fun --problem ode_fun"
    artifact_paths: "ode_fun/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1

  - label: "Flame graph (forward euler)"
    command:
      - "julia --project=perf perf/flame.jl --job_id forward_euler --problem fe"
    artifact_paths: "forward_euler/*"
    agents:
      config: cpu
      queue: central
      slurm_ntasks: 1
